name: conan-package

on:
  push:
    paths:
      - '**/*.proto'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakelists.txt'
      - '.github/workflows/conan-package.yml'
      - '.github/workflows/requirements*.txt'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@main
    secrets: inherit
